package:
  name: apache-activemq-artemis
  version: "2.39.0"
  epoch: 0
  description: ActiveMQ Artemis is the next generation message broker from Apache ActiveMQ.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash
      - openjdk-21-default-jdk
      - libaio
      - openssl
      - procps

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - coreutils
      - fontconfig-config
      - fontconfig-dev
      - libfontconfig1
      - maven
      - openjdk-21-default-jdk
      - openssl
      - procps

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/activemq-artemis
      tag: ${{package.version}}
      expected-commit: fb1c6e3217e7453226e2e441df776e7a880571e1

  - runs: |
      mvn -Prelease package -DskipTests -Drat.excludesFile=rat-exclusions.txt
      mkdir -p "${{targets.contextdir}}"/opt/activemq-artemis
      cp -r artemis-distribution/target/apache-artemis-${{package.version}}-bin/apache-artemis-${{package.version}}/* "${{targets.contextdir}}"/opt/activemq-artemis/

# subpackages:
#   - name: "${{package.name}}-compat"
#     description: "Compatibility package to place binaries in location expected by the container"
#     pipeline:
#       - runs: |
#           cp docker/docker-run.sh "${{targets.contextdir}}"/

# update:
#   enabled: true
#   github:
#     identifier: apache/tika
#     use-tag: true
#     tag-filter: 3.0.

# test:
#   environment:
#     contents:
#       packages:
#         - curl
#         - ${{package.name}}-compat
#         - openjdk-17-default-jvm
#   pipeline:
#     - name: "start server and verify endpoint"
#       runs: |
#         (
#         java -jar /tika-server-standard.jar &
#         ) && \
#         sleep 2 && \
#         curl -s http://localhost:9998/ | \
#         grep "<h1>Welcome to the Apache Tika 3.0.0 Server</h1>" && \
#         sleep 2 && \
#         echo "this is a test file!" > sample.txt && \
#         curl -X PUT --data-binary @sample.txt -H "Content-Type: text/plain" http://localhost:9998/tika | \
#         grep "this is a test file!"
