package:
  name: aws-c-compression
  version: "0.3.1"
  epoch: 0
  description: C99 implementation of huffman encoding/decoding
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - aws-c-common-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - samurai

pipeline:
  - uses: git-checkout
    with:
      expected-commit: f951ab2b819fc6993b6e5e6cfef64b1a1554bfc8
      repository: https://github.com/awslabs/aws-c-compression
      tag: v${{package.version}}

  - runs: |
      if [ "$CBUILD" != "$CHOST" ]; then
        CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
      fi
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_TESTING="$(want_check && echo ON || echo OFF)" \
        $CMAKE_CROSSOPTS
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: aws-c-compression-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/aws-c-compression "${{targets.subpkgdir}}"/usr/lib/
    description: aws-c-compression dev

test:
  pipeline:
    - uses: test/ldd-check
      with:
        packages: ${{package.name}}

update:
  enabled: true
  github:
    identifier: awslabs/aws-c-compression
    strip-prefix: v
    use-tag: true
