package:
  name: chainguard-source
  version: "1.0"
  epoch: 0
  description: "Fetch all sources referenced by a Chainguard Package or Image SBOM"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash
      - busybox
      - bzip2
      - cosign
      - jq
      - git
      - gnutar
      - gzip
      - wget
      - xz

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/chainguard-source
      expected-commit: faf5f38a88c69bc111e93adb753c2dfbf9cc5fd2
      tag: ${{package.version}}

  - runs: |
      cp -a chainguard-source ${{targets.destdir}}/usr/bin/chainguard-source

update:
  enabled: true
  github:
    identifier: chainguard-dev/chainguard-source
    use-tag: true

test:
  pipeline:
    - runs: |
        chainguard-source --help
        chainguard-source --yes --package hello-wolfi
