package:
  name: cis-operator
  version: "1.4.1"
  epoch: 0
  description: Helps to enable running CIS benchmark security scans on a Kubernetes cluster and generate compliance reports that can be downloaded
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/cis-operator
      tag: v${{package.version}}
      expected-commit: cae64d5d3766e725a29825d4fb7b2c63b62741f1

  - uses: go/bump
    with:
      deps: |-
        github.com/go-viper/mapstructure/v2@v2.3.0
        golang.org/x/net@v0.38.0

  - uses: go/build
    with:
      packages: .
      tags: netgo,osusergo
      ldflags: |
        -X github.com/rancher/cis-operator.Version=${{package.version}}
        -X github.com/rancher/cis-operator.GitCommit=$(git rev-parse HEAD)
      output: cis-operator

update:
  enabled: true
  github:
    identifier: rancher/cis-operator
    strip-prefix: v
