package:
  name: code-server-compat
  version: "4.98.2"
  epoch: 0
  description: 
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 32
    memory: 64Gi
  dependencies:
    runtime:
      - code-server
      - busybox
      - dumb-init
      - git
      - git-lfs
      - openssh-client
      - sudo
      - curl
      - htop
      - man-db
      - nano
      - procps
      - vim
      - wget

environment:
  contents:
    packages:
      - code-server
      - busybox
      - dumb-init
      - git
      - git-lfs
      - openssh-client
      - sudo
      - curl
      - htop
      - man-db
      - nano
      - procps
      - vim
      - wget

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/coder/code-server
      tag: v${{package.version}}
      expected-commit: e2c489dd00f163b1a8d959965b0c30c1a978a080
  - runs: |
      mkdir -p "${{targets.contextdir}}"/usr/bin
      cp ci/release-image/entrypoint.sh "${{targets.contextdir}}"/usr/bin/entrypoint.sh
      git lfs install
      mkdir -p "${{targets.contextdir}}"/etc/sudoers.d
      mkdir -p "${{targets.contextdir}}"/etc/fixuid
      echo "coder ALL=(ALL) NOPASSWD:ALL" >> "${{targets.contextdir}}"/etc/sudoers.d/nopasswd
      printf "user: coder\ngroup: coder\n" > "${{targets.contextdir}}"/etc/fixuid/config.yml
