package:
  name: code-server
  version: "4.98.2"
  epoch: 0
  description: A Kubernetes mutating webhook that makes direct secret injection into Pods possible.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/coder/code-server
      tag: v${{package.version}}
      expected-commit: e2c489dd00f163b1a8d959965b0c30c1a978a080

  - uses: patch
    with:
      series: patches/series

  - runs: |

# subpackages:
#   - name: "${{package.name}}-compat"
#     dependencies:
#       runtime:
#         - ${{package.name}}
#     pipeline:
#       - runs: |
#           mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
#           ln -s /usr/bin/vault-secrets-webhook ${{targets.subpkgdir}}/usr/local/bin/vault-secrets-webhook

# update:
#   enabled: true
#   github:
#     identifier: coder/code-server
#     strip-prefix: v
#     use-tag: true

# test:
#   environment:
#     contents:
#       packages:
#         - curl
#         - jq
#         - git
#         - wait-for-it
#     environment:
#       SECRET: root
#   pipeline:
#     - uses: test/kwok/cluster
#     - name: Test the app
#       runs: |