# Creates a base environment at /usr, so you need to change the root_prefix in config and explictly create a base env,
# instead you may use the conda-base package in wolfi-dev
package:
  name: conda
  version: 24.11.1
  epoch: 0
  description: "A system-level, binary package and environment manager running on all major operating systems and platforms."
  copyright:
    - license: BSD-3-Clause
  options:
    no-provides: true
    no-depends: true
  dependencies:
    provider-priority: 0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - py3-build-base
      - py3-charset-normalizer
      - py3-conda-package-handling
      - py3-conda-package-streaming
      - py3-hatch
      - py3-hatch-vcs
      - py3-hatchling
      - py3-idna
      - py3-libmambapy
      - py3-pycosat
      - py3-requests
      - py3-urllib3
      - py3-wheel
      - py3-zstandard
      - python3
      - wget
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/conda/conda
      tag: ${{package.version}}
      expected-commit: 1e025e1ac47914e470e140253f0ec69849535ca6

subpackages:
  - name: py3-conda
    description: python3 version of conda
    dependencies:
      runtime:
        - py3-archspec
        - py3-boltons
        - py3-conda-libmamba-solver
        - py3-conda-package-handling
        - py3-conda-package-streaming
        - py3-libmambapy
        - py3-packaging
        - py3-platformdirs
        - py3-pluggy
        - py3-pycosat
        - py3-requests
        - py3-ruamel-yaml
        - py3-tqdm
        - python3
    pipeline:
      - uses: py/pip-build-install
      - name: "move usr/bin executables for -bin"
        runs: |
          mkdir -p ./cleanup/
          mv ${{targets.contextdir}}/usr/bin ./cleanup/
      - uses: strip

  - name: py3-conda-bin
    description: Executable binaries for conda installed for python3
    dependencies:
      runtime:
        - py3-conda
      provides:
        - conda
      provider-priority: "312"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/
          mv ./cleanup/bin ${{targets.contextdir}}/usr/

  - name: ${{package.name}}-init
    description: Initializes conda
    dependencies:
      runtime:
        - bash
        - conda
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc/profile.d
          install -Dm755 init.sh ${{targets.subpkgdir}}/etc/profile.d/${{package.name}}-init.sh
    test:
      environment:
        contents:
          packages:
            - conda-base
      pipeline:
        - runs: |
            source /etc/profile.d/conda-init.sh
            conda install -y conda

  - name: ${{package.name}}-wrapper
    description: A wrapper that initializes conda before use
    dependencies:
      runtime:
        - ${{package.name}}-init
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          install -Dm755 wrapper.sh ${{targets.subpkgdir}}/usr/bin/${{package.name}}-wrapper
    test:
      environment:
        contents:
          packages:
            - conda-base
      pipeline:
        - runs: |
            conda-wrapper install -y conda

update:
  enabled: true
  github:
    identifier: conda/conda

test:
  pipeline:
    - runs: |
        conda --version
        conda info
        conda init
        conda create -n foo
        conda install -n foo numpy
        conda install -n foo --solver=classic requests
        conda --help
