package:
  name: docker-compose
  version: 2.29.0
  epoch: 0
  description: Define and run multi-container applications with Docker
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - btrfs-progs-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - containerd
      - coreutils
      - go
      - libseccomp-dev
      - libtool
      - linux-headers
      - lvm2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/docker/compose
      tag: v${{package.version}}
      expected-commit: 06bf339a42f59c0231aad5d0e0fd67d9496b7e60

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      DESTDIR=${{targets.destdir}}/usr/bin/ make build

test:
  environment:
    contents:
      packages:
        - docker-cli
  pipeline:
    - runs: docker compose --help

update:
  enabled: true
  github:
    identifier: docker/compose
    strip-prefix: v
    tag-filter: v
