package:
  name: falco-rules
  version: "5.0.0"
  epoch: 0
  description: Falco rule repository
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/falcosecurity/rules
      tag: falco-rules-${{package.version}}
      expected-commit: d919107be667675a816ec4fb6b8fea6f39445e46

  - runs: |
      install -Dm755 ./rules/falco_rules.yaml "${{targets.destdir}}"/etc/falco/falco_rules.yaml

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - falco-sandbox-rules-*
    - falco-incubating-rules-*
    - falco-deprecated-rules-*
    - application-rules-*
  github:
    identifier: falcosecurity/rules
    strip-prefix: falco-rules-
