package:
  name: fixuid
  version: "0.6.0"
  epoch: 0
  description: Go tool to change a Docker container's user/group and file permissions.
  copyright:
    - license: MIT
  checks:
    disabled:
      - setuidgid

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/boxboat/fixuid
      tag: v${{package.version}}
      expected-commit: c639d9b3d183248f8de031679654bf2146f88083

  - uses: go/build
    with:
      packages: .
      output: fixuid

  - runs: |
      mkdir -p ${{targets.contextdir}}/etc/fixuid
      chmod u+s ${{targets.contextdir}}/usr/bin/fixuid

update:
  enabled: true
  github:
    identifier: boxboat/fixuid
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        fixuid -h
        mkdir -p /etc/fixuid
        mkdir -p /var/run
        printf "user: root\ngroup: root\n" > /etc/fixuid/config.yml
    - name: run-fixuid
      with:
        start: "/usr/bin/fixuid"
        expected_output: |
          fixuid: runtime UID '0' already matches container user 'root' UID
