package:
  name: grafana-alloy
  version: 1.2.0
  epoch: 0
  description: OpenTelemetry Collector distribution with programmable pipelines
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/alloy
      tag: v${{package.version}}
      expected-commit: 7d95579015e121941001f0f06167e873dc7aabcc

  - uses: go/build
    with:
      packages: .
      output: grafana-alloy
      ldflags: -s -w

  - uses: strip

test:
  pipeline:
    - runs: |
        /usr/bin/grafana-alloy --version

update:
  enabled: true
  ignore-regex-patterns:
    - -rc
  github:
    identifier: grafana/alloy
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v
