package:
  name: hugo-extended
  version: "0.146.7"
  epoch: 0
  description: The world's fastest framework for building websites.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - libstdc++

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gohugoio/hugo
      tag: v${{package.version}}
      expected-commit: 1ad3d39dc4693434505fc81f91eed57333017e93

  - uses: go/build
    with:
      packages: .
      output: hugo
      tags: extended

  - uses: strip

update:
  enabled: true
  github:
    identifier: gohugoio/hugo
    strip-prefix: v

test:
  pipeline:
    ##GPT script test
    - name: Check Hugo version
      runs: |
        hugo version
    - name: Create a new Hugo site
      runs: |
        hugo new site test-site
        [ -d "test-site" ] # Check if the directory was created
    - name: Build the Hugo site
      runs: |
        cd test-site
        hugo
        [ -d "public" ] # Check if the public directory was created
