package:
  name: imlib2
  version: "1.12.5"
  epoch: 0
  description: Image manipulation library
  copyright:
    - license: Imlib2

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - freetype-dev
      - giflib-dev
      - libid3tag-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - libsm-dev
      - libwebp-dev
      - libxext-dev
      - tiff-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 35be438261c914e6ce90f06a3985fa7fea1c1e6b25b5607313e850b653015aa2
      uri: https://downloads.sourceforge.net/enlightenment/imlib2-${{package.version}}.tar.gz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: imlib2-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - imlib2
        - freetype-dev
        - libxext-dev
        - libsm-dev
    description: imlib2 dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

update:
  enabled: true
  release-monitor:
    identifier: 21676

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        imlib2_conv --version
        imlib2_load version
        imlib2_conv --help
        imlib2_load help
    - uses: test/tw/ldd-check
