package:
  name: kube-metrics-adapter
  version: 0.2.3
  epoch: 0
  description: General purpose metrics adapter for Kubernetes HPA metrics
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/zalando-incubator/kube-metrics-adapter
      expected-commit: 61d5880f8c26b137ffe19e55588c1de1a2bdd1cd
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      output: kube-metrics-adapter
      packages: main.go
      ldflags: -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.date=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ") -w -s

  - uses: strip

update:
  enabled: true
  github:
    identifier: zalando-incubator/kube-metrics-adapter
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-compat
  pipeline:
    - runs: |
        kube-metrics-adapter -h
