package:
  name: kuma
  version: 2.8.2
  epoch: 0
  description: A multi-zone service mesh for containers, Kubernetes and VMs.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kumahq/kuma
      tag: ${{package.version}}
      expected-commit: ffb0a135b8320cd474c503b785b43627d77a1338

subpackages:
  - name: kuma-cp
    pipeline:
      - uses: go/build
        with:
          packages: ./app/kuma-cp
          output: kuma-cp
      - uses: strip
    test:
      pipeline:
        - name: Verify kuma-cp
          runs: |
            kuma-cp --version

update:
  enabled: true
  github:
    identifier: kumahq/kuma
    use-tag: true
