package:
  name: libzen
  version: 0.4.41
  epoch: 0
  description: "ZenLib is a C++ utility library"
  copyright:
    - license: Zlib

environment:
  contents:
    packages:
      - busybox
      - build-base
      - libtool
      - pkgconf
      - pkgconf-dev
      - wolfi-baselayout
      - zlib-dev

pipeline:
  - name: Checkout ZenLib
    uses: git-checkout
    with:
      repository: https://github.com/MediaArea/ZenLib.git
      tag: v${{package.version}}
      expected-commit: 894980d3ecbc843d6ac685493f8f2ed5c2b6864c

  - name: Build and Install ZenLib
    runs: |
      ./autogen.sh
    working-directory: Project/GNU/Library

  - uses: autoconf/configure
    with:
      opts: --prefix=/usr
    working-directory: Project/GNU/Library

  - uses: autoconf/make
    working-directory: Project/GNU/Library
   
  - uses: autoconf/make-install
    with:
      opts: |
        DESTDIR="${{targets.destdir}}" install
    working-directory: Project/GNU/Library

update:
  enabled: true
  release-monitor:
    identifier: 1810

test:
  pipeline:
    - uses: test/tw/ldd-check
