package:
  name: llvm-libunwind-18
  version: 18.1.8
  epoch: 0
  description: LLVM version of libunwind library
  copyright:
    - license: MIT
  dependencies:
    provides:
      - llvm-libunwind=18

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang
      - cmake
      - gcc-12-default # needed for -nostdlib++
      - llvm-dev
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/llvm/llvm-project
      tag: llvmorg-${{package.version}}
      expected-commit: 3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff

  - runs: |
      CC=clang CXX=clang cmake -B build -G Ninja -Wno-dev -S libunwind \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCLANG_BUILT_STANDALONE=TRUE \
        -DLLVM_CONFIG=/usr/lib/llvm18/bin/llvm-config \
        -DCMAKE_MODULE_PATH=/home/build/cmake-src/Modules \
        -DLIBUNWIND_INSTALL_HEADERS=YES

  - runs: |
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

subpackages:
  - name: llvm-libunwind-18-static
    pipeline:
      - uses: split/static
    description: LLVM version of libunwind library (static library)
    dependencies:
      provides:
        - llvm-libunwind-static=18

  - name: llvm-libunwind-18-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - llvm-libunwind=18
      provides:
        - llvm-libunwind-dev=18
    description: LLVM version of libunwind library (development files)

update:
  enabled: true
  github:
    identifier: llvm/llvm-project
    strip-prefix: llvmorg-
    tag-filter: llvmorg-18.1.
    use-tag: true
