package:
  name: lua-resty-redis
  version: "0.32"
  epoch: 0
  description: "Lua redis client driver for the ngx_lua based on the cosocket API"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base
  environment:
    PREFIX: /usr

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openresty/lua-resty-redis.git
      tag: v${{package.version}}
      expected-commit: 11609088f4265a111d42203c6631e5fd0e86baf0

  - uses: autoconf/make-install

update:
  enabled: true
  github:
    identifier: openresty/lua-resty-redis
    strip-prefix: v
    use-tag: true
