package:
  name: mediainfolib
  version: 25.03
  epoch: 0
  description: "Utility for displaying technical and tag data for media files"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - busybox
      - build-base
      - libtool
      - pkgconf
      - pkgconf-dev
      - zlib-dev
      - libzen-dev

pipeline:
  - name: Checkout MediaInfoLib
    uses: git-checkout
    with:
      repository: https://github.com/MediaArea/MediaInfoLib.git
      tag: "v${{package.version}}"
      expected-commit: b1369cf34d6567aceac4f0c4208bc5caa0d4d2f7

  - name: Build and Install MediaInfoLib
    runs: |
      ./autogen.sh
    working-directory: Project/GNU/Library

  - uses: autoconf/configure
    with:
      opts: --prefix=/usr
    working-directory: Project/GNU/Library

  - uses: autoconf/make
    working-directory: Project/GNU/Library
   
  - uses: autoconf/make-install
    with:
      opts: |
        DESTDIR="${{targets.destdir}}" install
    working-directory: Project/GNU/Library

subpackages:
  - name: mediainfolib-dev
    description: "Development headers for mediainfolib"
    pipeline:
      - uses: split/dev
    test:
       pipeline:
         - uses: test/pkgconf

update:
  enabled: true
  release-monitor:
    identifier: 16249

test:
  pipeline:
    - uses: test/tw/ldd-check
