package:
  name: mediainfo
  version: 25.03
  epoch: 0
  description: "Utility for displaying technical and tag data for media files"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates
      - git
      - build-base
      - autoconf
      - automake
      - libtool
      - pkgconf
      - pkgconf-dev
      - glibc
      - wolfi-baselayout
      - zlib-dev
      - libzen
      - mediainfolib

pipeline:
  - name: Checkout MediaInfo
    uses: git-checkout
    with:
      repository: https://github.com/MediaArea/MediaInfo.git
      tag: "v${{package.version}}"
      expected-commit: 06f1b659f57c081fabdc91d3f3546b73206e171c

  - name: Autogen and Install MediaInfo
    runs: |
      pwd
      ls -la
      ./autogen.sh
      ./configure --prefix=/usr
      make
      make DESTDIR="${{targets.destdir}}" install
    working-directory: Project/GNU/CLI

subpackages:
  - name: "mediainfo-doc"
    description: "Documentation for mediainfo"
    pipeline:
      - runs: |
          mkdir -p "${{targets.destdir}}/usr/share/doc/mediainfo"
          cp -r MediaInfo/Documentation/* "${{targets.destdir}}/usr/share/doc/mediainfo/" || true

test:
  pipeline:
    - name: Test mediainfo
      runs: |
        mediainfo --version

update:
  enabled: true
  release-monitor:
    identifier: 8240

