package:
  name: mediainfo
  version: 25.03
  epoch: 0
  description: "Utility for displaying technical and tag data for media files"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - libzen
      - mediainfolib

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
      - http://host.docker.internal:8000
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates
      - build-base
      - libtool
      - pkgconf
      - pkgconf-dev
      - wolfi-baselayout
      - zlib-dev
      - libzen
      - mediainfolib

pipeline:
  - name: Checkout MediaInfo
    uses: git-checkout
    with:
      repository: https://github.com/MediaArea/MediaInfo.git
      tag: "v${{package.version}}"
      expected-commit: 06f1b659f57c081fabdc91d3f3546b73206e171c

  - name: Build and Install ZenLib
    runs: |
      ./autogen.sh
    working-directory: Project/GNU/CLI

  - uses: autoconf/configure
    with:
      opts: --prefix=/usr
    working-directory: Project/GNU/CLI

  - uses: autoconf/make
    working-directory: Project/GNU/CLI
   
  - uses: autoconf/make-install
    with:
      opts: |
        DESTDIR="${{targets.destdir}}" install
    working-directory: Project/GNU/CLI

test:
  pipeline:
    - name: Test mediainfo
      runs: |
        mediainfo --version

update:
  enabled: true
  release-monitor:
    identifier: 8240


