package:
  name: perl-parallel-pipes
  version: "0.201"
  epoch: 0
  description: friendly interface for Parallel::Pipes
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev
      - perl-extutils-config
      - perl-extutils-helpers
      - perl-extutils-installpaths
      - perl-module-build-tiny

pipeline:
  - uses: fetch
    with:
      expected-sha256: b73cbdd4202b29eab97e0c08dcd59d9273633610e8721cf449078656bd591a7c
      uri: https://cpan.metacpan.org/authors/id/S/SK/SKAJI/Parallel-Pipes-${{package.version}}.tar.gz

  - name: Build and Test
    runs: |
      # Not using perl pipeline since it doesn't use Makefile.PL
      export CFLAGS=$(perl -MConfig -E 'say $Config{ccflags}')
      perl Build.PL --installdirs=vendor

  - runs: |
      export CFLAGS=$(perl -MConfig -E 'say $Config{ccflags}')
      perl Build
      perl Build test

  - runs: |
      perl Build install --destdir=${{targets.destdir}}
      find ${{targets.destdir}} \( -name perllocal.pod -o -name .packlist \) -delete

update:
  enabled: true
  release-monitor:
    identifier: 12368

subpackages:
  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs
