package:
  name: perl-win32-shellquote
  version: "0.003001"
  epoch: 0
  description: Quote argument lists for Win32
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: aa74b0e3dc2d41cd63f62f853e521ffd76b8d823479a2619e22edb4049b4c0dc
      uri: https://cpan.metacpan.org/authors/id/H/HA/HAARG/Win32-ShellQuote-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

update:
  enabled: false
  exclude-reason: latest version has a `0.` which release-monitor does not pick up as a stable release - no github release either

subpackages:
  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs
