package:
  name: perl-app-cpanminus
  version: "1.7048"
  epoch: 0
  description: Get, unpack, build and install modules from CPAN
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 59b60907ab9fa4f72ca2004fbe6054911439ae9a906890b4d842a87b25f20f3c
      uri: https://cpan.metacpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

  - runs: |
      mv ${{targets.destdir}}/usr/bin/cpanm .
      install -Dpm0755 -t ${{targets.destdir}}/usr/bin ./cpanm

update:
  enabled: true
  release-monitor:
    identifier: 6748

subpackages:
  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs

test:
  environment:
    contents:
      packages:
        - build-base
        - perl-dev
  pipeline:
    - name: Smoke tests
      runs: |
        cpanm --version | grep "${{package.version}}"
    - runs: |
        cpanm HTTP::Server::Simple --verbose
