package:
  name: perl-cpan-distnameinfo
  version: "0.12"
  epoch: 0
  description: Perl module for extracting distribution names and versions from a distribution filename
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 2f24fbe9f7eeacbc269d35fc61618322fc17be499ee0cd9018f370934a9f2435
      uri: https://cpan.metacpan.org/authors/id/G/GB/GBARR/CPAN-DistnameInfo-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 6748

subpackages:
  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs
