package:
  name: perl-cpan-distnameinfo
  version: "0.12"
  epoch: 0
  description: Perl module for extracting distribution names and versions from a distribution filename
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

pipeline:
  - uses: fetch
    with:
      expected-sha256: 2f24fbe9f7eeacbc269d35fc61618322fc17be499ee0cd9018f370934a9f2435
      uri: https://cpan.metacpan.org/authors/id/G/GB/GBARR/CPAN-DistnameInfo-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  release-monitor:
    identifier: 6748

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - name: Smoke test
      runs: echo "use CPAN::DistnameInfo;" | perl
    - name: Ensure maker works
      runs: |
        mkdir -p authors/id/G/GB/GBARR
        curl -fsSLo authors/id/G/GB/GBARR/CPAN-DistnameInfo-${{package.version}}.tar.gz https://cpan.metacpan.org/authors/id/G/GB/GBARR/CPAN-DistnameInfo-${{package.version}}.tar.gz
        perl -l <<'EOF' > output.txt
        use CPAN::DistnameInfo;
        my $pathname = 'authors/id/G/GB/GBARR/CPAN-DistnameInfo-${{package.version}}.tar.gz';

        my $d = CPAN::DistnameInfo->new($pathname);
        print $dist      = $d->dist;
        print $version   = $d->version;
        print $maturity  = $d->maturity;
        print $filename  = $d->filename;
        print $cpanid    = $d->cpanid;
        print $distvname = $d->distvname;
        print $extension = $d->extension;
        print $pathname  = $d->pathname;
        EOF
        get_line() { cat output.txt | sed -n "${1}p"; }

        get_line 1 | grep "^CPAN-DistnameInfo$"
        get_line 2 | grep "^${{package.version}}$"
        get_line 3 | grep "^released$"
        get_line 4 | grep "^CPAN-DistnameInfo-${{package.version}}.tar.gz$"
        get_line 5 | grep "^GBARR$"
        get_line 6 | grep "^CPAN-DistnameInfo-${{package.version}}$"
        get_line 7 | grep "^tar.gz$"
        get_line 8 | grep "^authors/id/G/GB/GBARR/CPAN-DistnameInfo-${{package.version}}.tar.gz$"
