package:
  name: perl-class-tiny
  version: "1.008"
  epoch: 0
  description: Minimalist class construction
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

pipeline:
  - uses: fetch
    with:
      expected-sha256: ee058a63912fa1fcb9a72498f56ca421a2056dc7f9f4b67837446d6421815615
      uri: https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Class-Tiny-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 2704

subpackages:
  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - name: Smoke test
      runs: echo "use Class::Tiny qw( test_element_foobar );" | perl
    - name: Test class functionality
      runs: |
        tee Person.pm <<'EOF'
        package Person;
        use Class::Tiny qw( name );
        1;
        EOF

        tee Employee.pm <<'EOF'
        package Employee;
        use parent 'Person';
        use Class::Tiny qw( ssn ), {
          timestamp => sub { time }   # attribute with default
        };
        1;
        EOF

        install -Dpm0644 -t /usr/local/lib/perl5/site_perl/ ./*.pm

        perl -l <<'EOF' > output.txt
        use Employee;
        my $obj = Employee->new( name => "Larry", ssn => "111-22-3333" );
        print $obj->{name};
        print $obj->{ssn};
        # unknown attributes are silently ignored
        my $obj = Employee->new( name => "Larry", OS => "Linux" );
        print $obj->{OS}
        EOF
        get_line() { cat output.txt | sed -n "${1}p"; }

        get_line 1 | grep "^Larry$"
        get_line 2 | grep "^111-22-3333$"
        get_line 3 | grep "^$" # "OS" should be ignored
