package:
  name: perl-command-runner
  version: "0.201"
  epoch: 0
  description: run external commands and Perl code refs
  copyright:
    - license: Artistic-1.0-Perl OR GPL-1.0-or-later
  dependencies:
    runtime:
      - perl
      - perl-capture-tiny
      - perl-file-pushd
      - perl-string-shellquote
      - perl-win32-shellquote

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-capture-tiny
      - perl-dev
      - perl-extutils-config
      - perl-extutils-helpers
      - perl-extutils-installpaths
      - perl-file-pushd
      - perl-module-build-tiny
      - perl-string-shellquote
      - perl-win32-shellquote

pipeline:
  - uses: fetch
    with:
      expected-sha256: 38e3294ae9ffd015625d7746a0803cc329de92fb0f0edae9a29cd8232cf458d3
      uri: https://cpan.metacpan.org/authors/id/S/SK/SKAJI/Command-Runner-${{package.version}}.tar.gz

  - name: Build and Test
    runs: |
      # Not using perl pipeline since it doesn't use Makefile.PL
      export CFLAGS=$(perl -MConfig -E 'say $Config{ccflags}')
      perl Build.PL --installdirs=vendor

  - runs: |
      export CFLAGS=$(perl -MConfig -E 'say $Config{ccflags}')
      perl Build
      perl Build test

  - runs: |
      perl Build install --destdir=${{targets.destdir}}
      find ${{targets.destdir}} \( -name perllocal.pod -o -name .packlist \) -delete

update:
  enabled: true
  release-monitor:
    identifier: 17233
