package:
  name: perl-module-cpanfile
  version: "1.1004"
  epoch: 0
  description: Perl module for parsing cpanfiles
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 88efbe2e9a642dceaa186430fedfcf999aaf0e06f6cced28a714b8e56b514921
      uri: https://cpan.metacpan.org/authors/id/M/MI/MIYAGAWA/Module-CPANfile-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 3081

subpackages:
  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs
