package:
  name: perl-libwww
  version: "6.78"
  epoch: 0
  description: The World-Wide Web library for Perl
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl-encode-locale
      - perl-file-listing
      - perl-html-parser
      - perl-http-cookies
      - perl-http-date
      - perl-http-message
      - perl-http-negotiate
      - perl-lwp-mediatypes
      - perl-net-http
      - perl-try-tiny
      - perl-uri
      - perl-www-robotrules

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev
      - perl-encode-locale
      - perl-file-listing
      - perl-html-parser
      - perl-http-cookies
      - perl-http-date
      - perl-http-message
      - perl-http-negotiate
      - perl-lwp-mediatypes
      - perl-net-http
      - perl-try-tiny
      - perl-uri
      - perl-www-robotrules

pipeline:
  - uses: fetch
    with:
      expected-sha512: 8582a7f2fc2599056b61ade169563f9ced40c5a4193e297e5a26e2fe68b60f0bdff5c60197bd5b359ffde6f5c033393ad013b7cf68aaac790d73198fd63d2f99
      uri: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/libwww-perl-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: perl-libwww-doc
    pipeline:
      - uses: split/manpages
    description: perl-libwww manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  release-monitor:
    identifier: 3024

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        lwp-download --version
        lwp-dump version
        lwp-request help
        lwp-download --help
        lwp-dump help
        lwp-request version
