package:
  name: perl-clone
  version: "0.48_01"
  epoch: 0
  description: Clone perl module
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/garu/Clone.git
      tag: ${{package.version}}
      expected-commit: 87de6ce5ec1559590063520e6b69eff1dc4cc12f

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

subpackages:
  - name: perl-clone-doc
    pipeline:
      - uses: split/manpages
    description: perl-clone manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: garu/Clone
    use-tag: true

test:
  pipeline:
    - uses: test/tw/ldd-check
