package:
  name: perl-cpm
  version: "0.997023"
  epoch: 0
  description: get, unpack, build and install modules from CPAN
  copyright:
    - license: Artistic-1.0-Perl OR GPL-1.0-or-later
  dependencies:
    runtime:
      - build-base # TODO: figure out if really necessary
      # Depends on curl, wget, or whatever else, depends on user preference... - TODO: figure this out
      - curl
      - perl-class-tiny
      - perl-command-runner
      - perl-cpan-distnameinfo
      - perl-darwin-initobjc
      - perl-dev # TODO: figure out if really necessary
      - perl-extutils-config
      - perl-extutils-helpers
      - perl-extutils-installpaths
      - perl-file-copy-recursive
      - perl-file-which
      - perl-http-tinyish
      - perl-ipc-run3
      - perl-local-lib
      - perl-menlo
      - perl-menlo-legacy
      - perl-module-cpanfile
      - perl-module-cpmfile
      - perl-parallel-pipes
      - perl-parse-pmfile
      - perl-string-shellquote

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev
      - perl-extutils-config
      - perl-extutils-helpers
      - perl-extutils-installpaths
      - perl-module-build-tiny

pipeline:
  - uses: fetch
    with:
      expected-sha256: 5185cfba03bd48e9554663721172a387d66c81dc5e1a1f83b967aabd04614c95
      uri: https://cpan.metacpan.org/authors/id/S/SK/SKAJI/App-cpm-${{package.version}}.tar.gz

  - name: Build and Test
    runs: |
      # Not using perl pipeline since it doesn't use Makefile.PL
      export CFLAGS=$(perl -MConfig -E 'say $Config{ccflags}')
      perl Build.PL --installdirs=vendor

  - runs: |
      export CFLAGS=$(perl -MConfig -E 'say $Config{ccflags}')
      perl Build
      perl Build test

  - runs: |
      perl Build install --destdir=${{targets.destdir}}
      find ${{targets.destdir}} \( -name perllocal.pod -o -name .packlist \) -delete
      chmod +x ${{targets.destdir}}/usr/bin/cpm
      chmod 755 ${{targets.destdir}}/usr/bin/cpm
      # This shows 0755 on stat:
      # File: /home/build/melange-out/perl-cpm/usr/bin
      # Size: 96            Blocks: 0          IO Block: 4096   directory
      # Device: 2dh/45d    Inode: 15602097    Links: 3
      # Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
      # Access: 2025-06-02 18:48:06.123922247 +0000
      # Modify: 2025-06-02 18:48:06.155128459 +0000
      # Change: 2025-06-02 18:48:06.155128459 +0000
      stat ${{targets.destdir}}/usr/bin/cpm

test:
  pipeline:
    - name: Smoke tests
      runs: |
        perl /usr/bin/cpm --help | grep "a fast CPAN module installer"
        perl /usr/bin/cpm --version | grep "${{package.version}}"
    - runs: |
        perl /usr/bin/cpm install HTTP::Server::Simple --show-build-log-on-failure --with-recommends --test --verbose

update:
  enabled: true
  release-monitor:
    identifier: 8399
