package:
  name: perl-http-tinyish
  version: "0.19"
  epoch: 0
  description: Tiny compatible HTTP client wrappers
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: e9ce94a9913f9275d312ded4ddb34f76baf011b6b8d6029ff2871d5bd7bae468
      uri: https://cpan.metacpan.org/authors/id/M/MI/MIYAGAWA/HTTP-Tinyish-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 8355

subpackages:
  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs
