package:
  name: perl-extutils-makemaker-cpanfile
  version: "0.09"
  epoch: 0
  description: parses .pm file as PAUSE does
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 2c077607d4b0a108569074dff76e8168659062ada3a6af78b30cca0d40f8e275
      uri: https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/ExtUtils-MakeMaker-CPANfile-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 2869

subpackages:
  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs

test:
  environment:
    contents:
      packages:
        - curl
        - make
        - perl-module-cpanfile
  pipeline:
    - name: Smoke test
      runs: echo "use ExtUtils::MakeMaker;" | perl
    - name: Ensure maker works
      runs: |
        curl -fsSLo - https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/ExtUtils-MakeMaker-CPANfile-${{package.version}}.tar.gz | tar -xzvf - -C .
        cp */Makefile.PL .

        perl <<'EOF'
        use ExtUtils::MakeMaker;
        WriteMakefile();
        EOF

        make
        make test TEST_VERBOSE=1
        make install
        stat /usr/local/share/perl5/site_perl/ExtUtils/MakeMaker/CPANfile.pm
        stat /usr/local/share/man/man3/ExtUtils::MakeMaker::CPANfile.3pm
