package:
  name: perl-parse-pmfile
  version: "0.47"
  epoch: 0
  description: parses .pm file as PAUSE does
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-module-cpanfile

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev
      - perl-extutils-makemaker-cpanfile
      - perl-module-cpanfile

pipeline:
  - uses: fetch
    with:
      expected-sha256: 26817cf3d72e245452375dcff9e923a061ee0a40bbf060d3a08ebe60a334aaae
      uri: https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/Parse-PMFile-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 206460

subpackages:
  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs
