package:
  name: perl-menlo-legacy
  version: "1.9022"
  epoch: 0
  description: cpanm compatible CPAN installer
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: a6acac3fee318a804b439de54acbc7c27f0b44cfdad8551bbc9cd45986abc201
      uri: https://cpan.metacpan.org/authors/id/M/MI/MIYAGAWA/Menlo-Legacy-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 17243

subpackages:
  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs
