package:
  name: perl-menlo
  version: "1.9019"
  epoch: 0
  description: A CPAN client
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

pipeline:
  - uses: fetch
    with:
      expected-sha256: 3b573f68e7b3a36a87c860be258599330fac248b518854dfb5657ac483dca565
      uri: https://cpan.metacpan.org/authors/id/M/MI/MIYAGAWA/Menlo-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 8372

subpackages:
  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs
