package:
  name: perl-file-pushd
  version: "1.016"
  epoch: 0
  description: change directory temporarily for a limited scope
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - perl

pipeline:
  - uses: fetch
    with:
      expected-sha256: d73a7f09442983b098260df3df7a832a5f660773a313ca273fa8b56665f97cdc
      uri: https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/File-pushd-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: perl-file-which-doc
    pipeline:
      - uses: split/manpages
    description: perl-file-which manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  release-monitor:
    identifier: 2895
