package:
  name: py3-sympy
  version: 1.13.1
  epoch: 0
  description: Computer algebra system (CAS) in Python
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-mpmath

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b65c687588bab22db54c7984231cf72be115fb34
      repository: https://github.com/sympy/sympy
      tag: ${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import sympy

update:
  enabled: true
  github:
    identifier: sympy/sympy
    strip-prefix: sympy-
