package:
  name: py3-pydot
  version: 3.0.0
  epoch: 0
  description: Python interface to Graphviz's Dot
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-parsing
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-parsing
      - py3-setuptools
      - py3-wheel
      - python-3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pydot/pydot
      expected-commit: 84113fff774776a679d17fc900383c1fba87167b
      tag: v${{package.version}}

  - runs: |
      python3 -m gpep517 build-wheel --wheel-dir dist --output-fd 1
      python3 -m installer -d "${{targets.destdir}}" dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: pydot/pydot
    use-tag: true
    tag-filter: v
    strip-prefix: v
