package:
  name: py3-google-cloud-bigquery-storage
  version: "2.33.1"
  epoch: 0
  description: Google Cloud Bigquery Storage API client library
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: google-cloud-bigquery-storage
  import: google.cloud.bigquery_storage

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'

environment:
  contents:
    packages:
      - py3-supported-build-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: a7d9c212c76dc3f132f7899149a499d6790a7149
      repository: https://github.com/googleapis/python-bigquery-storage
      tag: v${{package.version}}

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      runtime:
        - py${{range.key}}-google-api-core
        - py${{range.key}}-proto-plus
        - py${{range.key}}-protobuf
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: test/metapackage

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}

update:
  enabled: true
  manual: false
  github:
    identifier: googleapis/python-bigquery-storage
    strip-prefix: v
