package:
  name: rke2-cloud-provider
  version: "1.33.1"
  epoch: 0
  description: cloud controller manager for RKE2
  copyright:
    - license: Apache-2.0


environment:
  contents:
    packages:
      - gawk
      - jq
      - file
      - gcc
      - git
      - make
      - clang
      - lld

vars:
  tag-suffix: ""

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/image-build-rke2-cloud-provider
      expected-commit: b24b25084b1c172f0b46a482c5dfca7987b9e2ed
      # Needs to be updated manually from https://github.com/rancher/image-build-rke2-cloud-provider/releases
      tag: v${{package.version}}-0.20250516163953-99d91538b132-build20250612

  - name: Get k3s version
    runs: |
        K3S_VERSION=$(go list -f '{{.Version}}' -m github.com/k3s-io/k3s)

  - uses: go/build
    with:
      packages: .
      output: cloud-controller-manager
      ldflags: -X github.com/k3s-io/k3s/pkg/version.Program=rke2 -X github.com/k3s-io/k3s/pkg/version.Version=$K3S_VERSION

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/local/bin"
          ln -sf /usr/bin/cloud-controller-manager ${{targets.subpkgdir}}/usr/local/bin/cloud-controller-manager

update:
  enabled: true
  github:
    identifier: rancher/image-build-rke2-cloud-provider
    strip-prefix: v
    strip-suffix: -.*
    tag-filter: v

test:
  pipeline:
    - runs: |
        rke2-cloud-provider --help
