package:
  name: rspamd
  version: "3.12.1"
  epoch: 1
  description: "Rapid spam filtering system"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - glib
      - libarchive
      - libevent
      - libicu77
      - libmagic
      - libsodium
      - luajit
      - openssl
      - pcre2
      - sqlite-libs
      - zlib

environment:
  contents:
    packages:
      - build-base
      - busybox
      - glib-dev
      - icu-dev
      - libarchive-dev
      - libsodium-dev
      - luajit-dev
      - openssl-dev
      - pcre2-dev
      - perl
      - ragel-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rspamd/rspamd
      tag: ${{package.version}}
      expected-commit: 6dbfca2fa06e1856a57fce7a6c90d5e0d0406b6a

  - uses: cmake/configure
    with:
      opts: |
        -DENABLE_PCRE2=ON \
        -DENABLE_LUAJIT=ON \
        -DINSTALL_WEBUI=OFF \
        -DINSTALL_EXAMPLES=OFF

  - uses: cmake/build

  - uses: cmake/install

  - runs: |
      mkdir -p "${{targets.destdir}}"/etc/rspamd

      # Copy instead of symlink to avoid build vs runtime path issues
      # symlinks may point to non-existent build paths and fail checks
      cp "${{targets.destdir}}"/usr/etc/rspamd/rspamd.conf "${{targets.destdir}}"/etc/rspamd/

      # Create required runtime directories
      install -d -m 755 "${{targets.destdir}}"/var/lib/rspamd
      install -d -m 755 "${{targets.destdir}}"/var/log/rspamd
      install -d -m 755 "${{targets.destdir}}"/run/rspamd

      install -d -m 700 "${{targets.destdir}}"/var/lib/rspamd/dkim
      install -d -m 755 "${{targets.destdir}}"/etc/rspamd/local.d
      install -d -m 755 "${{targets.destdir}}"/etc/rspamd/override.d

  - uses: strip

update:
  enabled: true
  github:
    identifier: rspamd/rspamd
    use-tag: true
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - bash
        - coreutils
  pipeline:
    - uses: test/tw/ldd-check
    - name: "Basic binary check"
      runs: |
        rspamd --version | grep -F -e "${{package.version}}"
        rspamc --help | grep -F -e "run rspamc client"
        rspamadm --version | grep -F -e "${{package.version}}"
    - name: "Test rspamadm administrative tools"
      runs: |
        rspamadm configtest | grep -F -e "syntax OK"
        rspamadm pw -p test123 | grep -q "\\$"
        rspamadm confighelp -k actions | grep -F -e "Configuration element: .actions"
