package:
  name: rspamd
  version: "3.12.1"
  epoch: 0
  description: "Rapid spam filtering system"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - glib
      - libarchive
      - libevent
      - libicu77
      - libmagic
      - libsodium
      - luajit
      - openssl
      - pcre2
      - sqlite-libs
      - zlib

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - curl-dev
      - gcc-14-default
      - glib-dev
      - icu-dev
      - libarchive-dev
      - libevent-dev
      - libmagic-dev
      - libsodium-dev
      - libuv-dev
      - linux-headers
      - luajit-dev
      - ninja
      - openssl-dev
      - pcre2-dev
      - perl
      - pkgconf
      - python-3
      - ragel
      - sqlite-dev
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rspamd/rspamd
      tag: ${{package.version}}
      expected-commit: 6dbfca2fa06e1856a57fce7a6c90d5e0d0406b6a

  - uses: cmake/configure
    with:
      opts: |
        -DENABLE_PCRE2=ON \
        -DENABLE_LUAJIT=ON \
        -DINSTALL_WEBUI=OFF \
        -DINSTALL_EXAMPLES=OFF

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

  - runs: |
      # Create required directories with proper permissions
      install -d -m 755 "${{targets.destdir}}"/etc/rspamd
      install -d -m 755 "${{targets.destdir}}"/var/lib/rspamd
      install -d -m 755 "${{targets.destdir}}"/var/log/rspamd
      install -d -m 755 "${{targets.destdir}}"/run/rspamd

update:
  enabled: true
  github:
    identifier: rspamd/rspamd
    use-tag: true
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - bash
        - coreutils
  pipeline:
    - uses: test/tw/ldd-check
    - name: "Basic binary check"
      runs: |
        rspamd --version
        rspamc --help
        rspamadm --version
    - name: "Test rspamadm administrative tools"
      runs: |
        rspamadm configtest
        rspamadm pw -p test123 | grep -q "\\$"
        rspamadm confighelp -k actions
