package:
  name: seaweedfs
  version: 3.69
  epoch: 0
  description: SeaweedFS is a fast distributed storage system for blobs, objects, files.
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"
    GODEBUG: http2client=0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/seaweedfs/seaweedfs
      tag: ${{package.version}}
      expected-commit: ac6fd36c06f9cd6740cb2ff7e97c1ba92d55bf2c

  - uses: go/build
    with:
      packages: ./weed
      output: weed
      ldflags: |
        -s -w -extldflags -static -X github.com/seaweedfs/seaweedfs/weed/util.COMMIT=$(git rev-parse HEAD)

  - uses: strip

test:
  pipeline:
    - name: "version command"
      runs: weed version

update:
  enabled: true
  github:
    identifier: seaweedfs/seaweedfs
