package:
  name: secrets-store-csi-driver-provider-aws
  version: "2.0.0"
  epoch: 0
  description: AWS Secrets Manager and AWS Systems Manager Parameter Store provider for the Secret Store CSI Driver.
  copyright:
    - license: Apache-2.0
  dependencies:
    # REMOVE_POST_USRMERGE - https://github.com/orgs/wolfi-dev/discussions/40270
    provides:
      - ${{package.name}}-compat=${{package.full-version}}
    runtime:
      - merged-bin
      - wolfi-baselayout

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/aws/secrets-store-csi-driver-provider-aws
      tag: secrets-store-csi-driver-provider-aws-${{package.version}}
      expected-commit: b88cf58e8d5946a373cfb821309fc9edf288afd5

  - runs: |
      # Our global LDFLAGS conflict with a Makefile parameter
      unset LDFLAGS
      # The current release seems to have an invalid go mod file
      go mod tidy
      make build ARCHITECTURES=$(go env GOARCH)
      mkdir -p ${{targets.destdir}}/usr/bin
      cp _output/secrets-store-csi-driver-provider-aws-* ${{targets.destdir}}/usr/bin/secrets-store-csi-driver-provider-aws

  - uses: strip

update:
  enabled: true
  github:
    identifier: aws/secrets-store-csi-driver-provider-aws
    strip-prefix: secrets-store-csi-driver-provider-aws-
    use-tag: true
    tag-filter: secrets-store-csi-driver-provider-aws-

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        secrets-store-csi-driver-provider-aws --help
