package:
  name: smartmontools
  version: "7.4"
  epoch: 0
  description: Control and monitor S.M.A.R.T. enabled hard drives
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - libcap-ng-dev
      - linux-headers
      - systemd-dev

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+)\.(\d+)$
    replace: ${1}_${2}
    to: smartmontools-tag-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/smartmontools/smartmontools
      tag: RELEASE_${{vars.smartmontools-tag-version}}
      expected-commit: 0c0bada5eedb759c9d7bb50ff54959cf0809c5a9

  - working-directory: smartmontools
    uses: autoconf/configure
    with:
      opts: |
        --sbindir=/usr/bin

  - working-directory: smartmontools
    uses: autoconf/make

  - working-directory: smartmontools
    uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/share/doc
          mv ${{targets.destdir}}/usr/share/doc/smartmontools ${{targets.contextdir}}/usr/share/doc
    description: ${{package.name}} manpages
    test:
      pipeline:
        - uses: test/docs

test:
  environment: {}
  pipeline:
    - name: Verify smartmontools installation
      runs: |
        smartctl --version | grep "${{package.version}}"

update:
  enabled: true
  version-transform:
    - match: ^(\d+)_(\d+)$
      replace: ${1}.${2}
  github:
    identifier: smartmontools/smartmontools
    strip-prefix: "RELEASE_"
    use-tag: true
