package:
  name: sonobuoy-systemd-logs
  version: "0.4.0"
  epoch: 0
  description: Sonobuoy 
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash
      # chroot is needed - https://github.com/vmware-tanzu/sonobuoy-plugins/blob/main/systemd-logs/get_systemd_logs.sh#L24 
      - coreutils
      - systemd
      - qemu

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/vmware-tanzu/sonobuoy-plugins
      branch: main
      expected-commit: b2b323cbdc7115c7a41a236c457d977271aa74c1
      depth: 1

  - name: Gather files for the package
    working-directory: systemd-logs
    runs: |
      install get_systemd_logs.sh "${{targets.contextdir}}"/get_systemd_logs.sh

# subpackages:
#   - name: ${{package.name}}-compat
#     description: "Compatibility package for the binary"
#     pipeline:
#       - runs: |
#           mkdir -p ${{targets.contextdir}}
#           ln -sf /usr/bin/sonobuoy ${{targets.contextdir}}/sonobuoy
#     test:
#       pipeline:
#         - runs: |
#             test "$(readlink /sonobuoy)" = "/usr/bin/sonobuoy"

update:
  enabled: false
  exclude-reason: No releases or tags on source to watch

test:
  pipeline:
    - name: "Test sonobuoy systemd-logs script"
      runs: |
        /usr/lib/systemd/systemd-journald > /tmp/logs 2>&1 &
        sleep 2
        echo "Test entry from systemd-cat" | systemd-cat
        install -d /tmp/results
        CHROOT_DIR="/" /get_systemd_logs.sh
        grep -q "Test entry from systemd-cat" /tmp/results/systemd-logs.log
