package:
  name: tensorflow-core
  description: Framework for data-graph oriented computing (core libraries, oneDNN build)
  version: 2.18.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 65
    memory: 64Gi

vars:
  bazel-common-opts: --bazelrc=.tf_configure.bazelrc build --config=mkl_threadpool --config=opt
  import: tensorflow

environment:
  contents:
    packages:
      - bash
      - bazelisk
      - bazelisk-default
      - build-base
      - c-ares-dev
      - clang-16
      - clang-16-dev
      - coreutils
      - curl-dev
      - cython~0
      - gcc-12-default
      - giflib-dev
      - hdf5
      - hdf5-dev
      - icu-dev
      - isl-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - libstdc++-12
      - libstdc++-12-dev
      - llvm-lld-16-dev
      - llvm16
      - llvm16-dev
      - mpc-dev
      - openjdk-11-default-jdk
      - openssf-compiler-options
      - openssl-dev
      - patchelf
      - perl
      - py3-gpep517
      - py3-installer
      - py3-keras-applications
      - py3-keras-preprocessing
      - py3-packaging
      - py3-pybind11
      - py3-pybind11-dev
      - py3-requests
      - py3-setuptools
      - py3-wheel
      - python-3-dev
      - wolfi-base
      - zlib-dev
  environment:
    PYTHON_BIN_PATH: /usr/bin/python
    TF_PYTHON_VERSION: 3.12
    USE_DEFAULT_PYTHON_LIB_PATH: 1
    TF_NEED_JEMALLOC: 1
    TF_NEED_KAFKA: 1
    TF_NEED_OPENCL_SYCL: 0
    TF_NEED_AWS: 1
    TF_NEED_GCP: 1
    TF_NEED_HDFS: 1
    TF_NEED_S3: 1
    TF_ENABLE_XLA: 1
    TF_NEED_GDR: 0
    TF_NEED_VERBS: 0
    TF_NEED_OPENCL: 0
    TF_NEED_MPI: 0
    TF_NEED_TENSORRT: 0
    TF_NEED_NGRAPH: 0
    TF_NEED_IGNITE: 0
    TF_NEED_ROCM: 0
    TF_SYSTEM_LIBS: "boringssl,curl,gif,icu,libjpeg_turbo,nasm,png,zlib,cython"
    TF_SET_ANDROID_WORKSPACE: 0
    TF_DOWNLOAD_CLANG: 0
    TF_NEED_CUDA: 0
    TF_CUDA_CLANG: 0
    CLANG_CUDA_COMPILER_PATH: /usr/bin/clang
    CC_OPT_FLAGS: "-O3"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tensorflow/tensorflow
      expected-commit: 6550e4bd80223cdb8be6c3afd1f81e86a4d433c3
      tag: v${{package.version}}

  - runs: |
      ./configure

      bazel ${{vars.bazel-common-opts}} //tensorflow:libtensorflow.so //tensorflow:libtensorflow_cc.so //tensorflow:install_headers //tensorflow:libtensorflow_framework.so

  - runs: |
      install -d "${{targets.destdir}}"/usr/include/tensorflow
      cp -r bazel-bin/tensorflow/include/* "${{targets.destdir}}"/usr/include/tensorflow/

      _pkgver=${{package.version}}

      tensorflow/c/generate-pc.sh --prefix=/usr --version=${_pkgver}
      sed -e 's@/include$@/include/tensorflow@' -i tensorflow.pc -i tensorflow_cc.pc
      install -Dm644 tensorflow.pc "${{targets.destdir}}"/usr/lib/pkgconfig/tensorflow.pc
      install -Dm644 tensorflow_cc.pc "${{targets.destdir}}"/usr/lib/pkgconfig/tensorflow_cc.pc

      install -Dm755 bazel-bin/tensorflow/libtensorflow.so "${{targets.destdir}}"/usr/lib/libtensorflow.so.${_pkgver}
      ln -s libtensorflow.so.${_pkgver} "${{targets.destdir}}"/usr/lib/libtensorflow.so.${_pkgver:0:1}
      ln -s libtensorflow.so.${_pkgver:0:1} "${{targets.destdir}}"/usr/lib/libtensorflow.so

      install -Dm755 bazel-bin/tensorflow/libtensorflow_cc.so "${{targets.destdir}}"/usr/lib/libtensorflow_cc.so.${_pkgver}
      ln -s libtensorflow_cc.so.${_pkgver} "${{targets.destdir}}"/usr/lib/libtensorflow_cc.so.${_pkgver:0:1}
      ln -s libtensorflow_cc.so.${_pkgver:0:1} "${{targets.destdir}}"/usr/lib/libtensorflow_cc.so

      install -Dm755 bazel-bin/tensorflow/libtensorflow_framework.so "${{targets.destdir}}"/usr/lib/libtensorflow_framework.so.${_pkgver}
      ln -s libtensorflow_framework.so.${_pkgver} "${{targets.destdir}}"/usr/lib/libtensorflow_framework.so.${_pkgver:0:1}
      ln -s libtensorflow_framework.so.${_pkgver:0:1} "${{targets.destdir}}"/usr/lib/libtensorflow_framework.so

      install -Dm644 tensorflow/c/c_api.h "${{targets.destdir}}"/usr/include/tensorflow/tensorflow/c/c_api.h
      install -Dm644 LICENSE "${{targets.destdir}}"/usr/share/licenses/${pkgname}/LICENSE

  - uses: strip

subpackages:
  - name: py3-tensorflow-core
    description: Tensorflow Python API
    dependencies:
      runtime:
        - py3-absl-py
        - py3-astunparse
        - py3-flatbuffers
        - py3-gast
        - py3-ml-dtypes
        - py3-numpy
        - py3-opt-einsum
        - py3-protobuf
        - py3-requests
        - py3-setuptools
        - py3-six
        - py3-termcolor
        - py3-wrapt
        - tensorflow-core
    pipeline:
      - runs: |
          bazel ${{vars.bazel-common-opts}} //tensorflow/tools/pip_package:wheel
          mkdir /home/build/pip-pkg-tmp
          find bazel-bin/tensorflow/tools/pip_package -iname "*.whl" -exec cp {} /home/build/pip-pkg-tmp \;
      - runs: |
          WHEEL_PACKAGE=$(find /home/build/pip-pkg-tmp -name "tensor*.whl")
          python -m installer --destdir="${{targets.contextdir}}" $WHEEL_PACKAGE
      - runs: |
          _pyver=$(python -c 'import sys; print(str(sys.version_info[0]) + "." + str(sys.version_info[1]))')
          _pypath="/usr/lib/python${_pyver}"
          find "${{targets.contextdir}}"${_pypath} -name "libtensorflow*.so*" -exec rm -rf '{}' +
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.12
            import: ${{vars.import}}

  - name: tensorflow-dev
    description: Tensorflow development headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf

update:
  enabled: true
  github:
    identifier: tensorflow/tensorflow
    strip-prefix: v
    tag-filter: v
