package:
  name: terragrunt
  version: 0.62.1
  epoch: 0
  description: Thin wrapper for Terraform providing extra tools
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - terraform

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - mockery

pipeline:
  - uses: git-checkout
    with:
      expected-commit: a7948a6288da1ee3b206438c5811ae397c56450c
      repository: https://github.com/gruntwork-io/terragrunt
      tag: v${{package.version}}

  - runs: go generate ./...

  - uses: go/build
    with:
      output: terragrunt
      packages: .
      ldflags: "-X  github.com/gruntwork-io/go-commons/version.Version=v${{package.version}}"

  - uses: strip

test:
  pipeline:
    - name: Verify terragrunt
      runs: |
        set -o pipefail
        terragrunt --version | grep "${{package.version}}"

update:
  enabled: true
  github:
    identifier: gruntwork-io/terragrunt
    strip-prefix: v
    use-tag: true
    tag-filter: v
