package:
  name: vault-secrets-webhook
  version: "1.21.4"
  epoch: 0
  description: A Kubernetes mutating webhook that makes direct secret injection into Pods possible.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:


pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bank-vaults/vault-secrets-webhook
      tag: v${{package.version}}
      expected-commit: be52ffa2ad14b492036e814fb922b690c4a6d8e6

  - uses: go/bump
    with:
      deps: |-
        github.com/go-jose/go-jose/v4@v4.0.5
        golang.org/x/crypto@v0.36.0
        golang.org/x/net@v0.37.0
        golang.org/x/oauth2@v0.28.0

  - uses: go/build
    with:
      packages: .
      output: webhook

update:
  enabled: true
  github:
    identifier: bank-vaults/vault-secrets-webhook
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - curl
        - kwok
        - kwokctl
        - vault
        - jq
  pipeline:
    - uses: test/kwok/cluster
    - name: Install, configure, and add a secret to vault
      runs: |
        vault server -dev -dev-root-token-id $VAULT_TOKEN -dev-listen-address="0.0.0.0:8200" &
        sleep 3s # vault startup
        vault auth enable approle
        vault secrets enable -path=kvv2 kv-v2
        vault policy write webapp - <<EOF
        path "kvv2/data/webapp/config" {
          capabilities = ["read", "list", "update", "create"]
        }
        EOF
        vault write auth/approle/role/role1 \
          policies=webapp \
          ttl=24h
        vault kv put kvv2/webapp/config username="static-user" password="static-password"
    - name: Run the vault-secrets-webhook 
      runs: |
        mkdir -p /var/run/secrets/kubernetes.io/serviceaccount
        echo "default" > /var/run/secrets/kubernetes.io/serviceaccount/namespace
        webhook &
    - name: Add a deployment with mutating  
