package:
  name: vectorscan
  version: "5.4.12"
  epoch: 0
  description: High-performance regular expression matching library
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - busybox
      - pcre-dev
      - ragel
      - samurai
      - sqlite-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/VectorCamp/vectorscan
      tag: vectorscan/${{package.version}}
      expected-commit: b585ad466658624bb31fb1d194cdb168df34833c

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: vectorscan dev
    dependencies:
      runtime:
        - vectorscan
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf

  - name: ${{package.name}}-doc
    description: vectorscan documentation
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  github:
    identifier: VectorCamp/vectorscan
    tag-filter: vectorscan
    strip-prefix: vectorscan/
