package:
  name: wolfi-keys
  version: 1
  epoch: 9
  description: "Wolfi signing keyring"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox

pipeline:
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"/etc/apk/keys
      install -m644 wolfi-signing.rsa.pub "${{targets.destdir}}"/etc/apk/keys

      for i in x86_64 aarch64; do
        mkdir -p "${{targets.destdir}}"/usr/share/apk/keys/${i}
        install -m644 wolfi-signing.rsa.pub "${{targets.destdir}}"/usr/share/apk/keys/${i}/wolfi-signing.rsa.pub
      done

update:
  enabled: false

test:
  pipeline:
    - runs: |
        # Make sure key file matches expected format
        for i in /usr/share/apk/keys/*/wolfi-signing.rsa.pub; do
          head -n1 $i | grep "^-----BEGIN PUBLIC KEY-----"
          grep -v "^-" $i | grep "^[a-zA-Z0-9/+=]\+$"
          tail -n1 /usr/share/apk/keys/*/wolfi-signing.rsa.pub | grep "^-----END PUBLIC KEY-----"
        done
        apk update
        # Verify what should be a good signature
        apk verify /var/cache/apk/APKINDEX.*.tar.gz
        # Now, tamper with a signature, and ensure the signature does not verify
        d=$(mktemp -d)
        cd "$d"
        tar xf /var/cache/apk/APKINDEX.*.tar.gz
        sed -i -e "1 s/^C:......../C:abcdefgh/" APKINDEX
        tar zcf APKINDEX.bad.tar.gz .SIGN.RSA256.wolfi-signing.rsa.pub APKINDEX DESCRIPTION
        # This must fail, due to the signature tampering
        (apk verify APKINDEX.bad.tar.gz || true) | grep -i "BAD signature"
