package:
  name: wolfi-base
  version: 1
  epoch: 7
  description: "Wolfi base metapackage"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - apk-tools
      - busybox
      - wolfi-keys

environment:
  contents:
    packages:
      - busybox

pipeline:
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"

test:
  pipeline:
    - name: "Commands exist"
      runs: |
        for x in apk sh ; do
          which $x
          type $x
          command -v $x
        done
    - name: "Commands do not exist"
      runs: |
        for x in curl git wget; do
          which $x && echo "$x found but should not be installed" && exit 1
          type $x && echo "$x found but should not be installed" && exit 1
          command -v $x && echo "$x found but should not be installed" && exit 1
        done

update:
  enabled: false
