package:
  name: zetasql
  version: 2024.11.1
  epoch: 0
  description: ZetaSQL - Analyzer Framework for SQL
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 33
    memory: 100Gi

vars:
  openjdk-version: 23

environment:
  contents:
    packages:
      - bash
      - bazel-7
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - libxml2 # Required by downloaded llvm toolchain
      - openjdk-${{vars.openjdk-version}}-default-jdk
      - patch
      - python3
      - tzdata
      - wolfi-baselayout
  environment:
    BAZEL_ARGS:
    EXTRA_BAZEL_ARGS: "--tool_java_runtime_version=local_jdk"
    JAVA_HOME: /usr/lib/jvm/java-${{vars.openjdk-version}}-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/google/zetasql
      tag: ${{package.version}}
      expected-commit: a516c6b26d183efc4f56293256bba92e243b7a61

  - uses: patch
    with:
      patches: multi-arch-for-linux.patch dev_lsp-to-github.patch llvm-specify-url.patch strip-nonlatin.patch

  - runs: |
      cd zetasql
      bazel build --verbose_failures ${BAZEL_ARGS} $EXTRA_BAZEL_ARGS -c opt ...
      # TODO need to copy whats required after this from either bazel-bin or bazel-out

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - zetasql

update:
  enabled: true
  github:
    identifier: google/zetasql
    use-tag: true
